name: "Dev Terraform Workflow (OIDC)"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write    # required for OIDC
  contents: read

jobs: 
  terraform-init-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: environments/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: c7135aa6-5c0c-4b33-a148-10aa1572b218
          tenant-id: de80a58f-1610-4908-a1a7-862be272a38c
          subscription-id: 0f48ce1f-16d2-42ba-8b4f-0bef1a58b563 
          allow-no-subscriptions: true


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -no-color -input=false -out=tfplan

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: environments/dev/tfplan

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-init-plan
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: environments/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: c7135aa6-5c0c-4b33-a148-10aa1572b218
          tenant-id: de80a58f-1610-4908-a1a7-862be272a38c
          subscription-id: 0f48ce1f-16d2-42ba-8b4f-0bef1a58b563 
          allow-no-subscriptions: true
          federated-token: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init -input=false

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: environments/dev

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
