name: "Infra Pipeline Kuch Bhi"

on: workflow_dispatch

permissions:
  id-token: write
  contents: read
  
jobs: 
  terraform-job:
    runs-on: self-hosted
    steps: 
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: ff27bcf6-f60c-4a57-8b01-8eee5de2a9cd
          tenant-id: 0f7010fd-209e-4344-8457-043ffb37143b
          subscription-id: 1075ec7a-b17a-4f37-bf3f-9d68c4506dc1
            
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
